### ISSUE TITLE
Broken Link on Lesson 3

### ISSUE THREAD

**Issue by caranha** [fcampelo/Design-and-Analysis-of-Experiments#1]
When showing that the mean and variance estimators are unbiased, page 10 links to:

http://www.public.iastate.edu/errors/inactive.html

But this link has been taken down.

**Comment by fcampelo** [comment]
Thanks Claus! :+1: 

A pity that document is no longer available (any copies of it seem to be [behind CourseHero's paywall](https://www.coursehero.com/file/6746386/Unbiasedness-of-Sample-Mean-and-Variance/) ).  

Anyway, I found [another document](http://isites.harvard.edu/fs/docs/icb.topic515975.files/Proof%20that%20Sample%20Variance%20is%20Unbiased.pdf) with the proof that the sample variance is unbiased, placed a copy within our Reference Material folder (with full attribution, of course) and changed the link accordingly! 

Cheers,
Felipe

**Comment by caranha** [comment]
Awesome! :-) I will start forking and sending pull requests to your repository with typos and stuff in the future :-D
