### ISSUE TITLE
Ch. 6 - Rejection Threshold => 1-alpha/2 ao invés de alpha/2 no slide 8

### ISSUE THREAD

**Issue by tatatupi** [fcampelo/Design-and-Analysis-of-Experiments#15]
Alterar na linha 166:

De:
We'll reject $H_0$ at the $(1-\alpha)$ confidence level if $|t_0|\geq t_{**\alpha/2**; (n_1+n_2-2)}$

Para:
We'll reject $H_0$ at the $(1-\alpha)$ confidence level if $|t_0|\geq t_{**1-\alpha/2**; (n_1+n_2-2)}$

**Comment by fcampelo** [comment]
Fixed, thanks!
